### ISSUE TITLE
[BUG] intent to grab :hand: 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10113]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game  Version
- 100461 - 23.10.07.15

### I was
Server (local Host)
HOP
On Ministation 
### OS
Linux
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?
the enter intention, if selected from the intention menu or via keyboard shortcut "3", does not work.

only Ctrl Clic works

**Comment by MaxIsJoe** [comment]
This is not a bug, and grab intent is already addressed multiple times.

**Comment by Fr-Dae** [comment]
it's stupid to have a MENU with a BUTTON that doesn't do what it says on the button.

the button is called "grab". 


again not Solved
