### ISSUE TITLE
Shuttle lerping is jerky

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2423]
# Description
We need a better formula for shuttle lerping as it doesn't behave well at low speeds: ship doesn't even appear to move for a couple of seconds while it's supposed to start, and then proceeds with speed fluctuations:
![GIF](https://user-images.githubusercontent.com/10403536/70225874-c563f280-1747-11ea-9956-c5be276d35a0.gif)

It needs to be smooth (no jerking or rubberbanding) and working at all speeds

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get in the mining shuttle and make sure it has a plasma tank connected
2. Make sure speed is set to lowest
3. Start the ship

**Comment by chairbender** [comment]
@fomalsd I touched matrix movement recently, is this still not working how you want?

**Comment by chairbender** [comment]
can confirm it still lerps wonkily

**Comment by chairbender** [comment]
I'm taking this ticket, so transferring bounty to  #2298

**Comment by DooblyNoobly** [comment]
still happening, reopened

**Comment by AtnerNT** [comment]
Has this been fixed by @MaxIsJoe ?

**Comment by MaxIsJoe** [comment]
> Partially addresses https://github.com/unitystation/unitystation/issues/2423

> Reduced the amount of jitter moving shuttles have significantly.

It's not fixed yet, but it will be once I work on the new shuttle movement.

**Comment by MaxIsJoe** [comment]
All hail the orange fox, for he has cured this issue.
