### ISSUE TITLE
Voting "no" means "yes"

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2911]
Regardless of what you pick in a vote for round restart, it counts as "yes"

**Comment by daalta** [comment]
Fixed it, PRing soon.

**Comment by JesterX666** [comment]
Still doesn't work.  Working on it.  It's even reproductible in standalone.

Steps to reproduce : 

1. Connect
2. Vote no
3. The round restarts

**Comment by JesterX666** [comment]
Server was not recompiled since integration of PR.
