### ISSUE TITLE
Unable to merge any stackables stackables on build client.

### ISSUE THREAD

**Issue by Necromunger** [unitystation/unitystation#3206]
In build versions of unitystation some players cannot merge any stackable items together.

This issue does not seem to happen in the unity editor.

The hover over color system also appears to not show the correct color either.

Instead of the merge blue/teal color it will show as magenta or brown hover color.

This issue is specific some some set of machines, not all users experience this issue while some do reliably.

**Comment by JesterX666** [comment]
A similar issue was fixed in Stacking stopped working #2979.

**Comment by ThatDan123** [comment]
Hasnt been reported recently, so i feel this has been fixed.

**Comment by ThatDan123** [comment]
Turns out this might still happen with some stackable items, inconsistently.

**Comment by NoooneyDude** [comment]
Closing for a similar reason as described in #3386.
