### ISSUE TITLE
You should be able to crawl around after slipping over.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4665]
## Description
Right now if you slip for whatever reason be it a banana, lube, atmospherics, coming out of a disposals outlet, or after extinguishing yourself by rolling, you will be laying on the ground unable to move. This is quite unfun due to the length of time you have to wait to get back up (especially after stop, dropping, and rolling) and potentially dangerous (you can end up on a conveyor belt that leads directly into outer space).

In /tg/, if you fall over due to the above reasons (atmos not included) you'll still be able to crawl around till you automatically (or manually) get back up. This lets you get off conveyor belts, and lets you reposition should you slip for whatever reason. Another thing to note is that you can actually crawl in Unitystation at the moment, but only while in (soft) crit for some reason. It's possible to slip over and rendered unable to move until you get put into crit and suddenly become able to crawl.

**Comment by NoooneyDude** [comment]
Is this resolved by #6252?

**Comment by PerfectTangent** [comment]
I don't think so. crawling hasn't been integrated with slipping or stuns in any way. Lemme test to be sure.

**Comment by PerfectTangent** [comment]
this is still an issue. slipping needs to be integrated with crawling.
