### ISSUE TITLE
Clothing not showing on players (Sync issue)

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4816]
Report from the discord:

Naked players seems to randomly start appearing for certain players on round starts.

The bug seems to affect all clothing including belts and backpacks, duffel bags and satchels of all kind. The person appears to be naked completely to socks and underwear, yet all the clothing is there and the player sees everything else normal or shares the same problem of seeing others naked. Just a visual bug, not gameplay.

The bandaid fix I learned from others was to simply wait for them to change what they wear or ask the people who are "naked" to take their clothes off and put 'em on again. That usually seems to work at least for me. Also heard relogging should help, yet for me whnever it happened it didn't work unlike taking the clothes off and back on again.

-Need someone to see if this is easily reproducible.

-Also might have been fixed on staging (Latest: Bods sprite networking), so needs to be tested on there too. 

EDIT: Still happens on staging see image in next post

**Comment by ThatDan123** [comment]
![image](https://user-images.githubusercontent.com/56727168/91727280-5d88ee00-eb99-11ea-8600-488120f053af.png)

**Comment by NoooneyDude** [comment]
Fixed by #5024

**Comment by corp-0** [comment]
I just joined a round in solidarity (latest build 4114) and this is still happening.

**Comment by NoooneyDude** [comment]
Has anyone seen this issue occur recently?

**Comment by corp-0** [comment]
I haven't heard anyone mentioning it but I don't think we have done anything to solve it either

**Comment by PerfectTangent** [comment]
I just experienced this issue again while running the latest build with a host and client. I logged out as the client and rejoin. The rejoining client appeared naked to the client, but not the host. This is definitely still an issue.

**Comment by NoooneyDude** [comment]
Feel free to reopen this if you see this again since #6002. However, the more recent encounters described here are likely due to a runtime error elsewhere, such as when spawning, which interrupts the code execution before it can sort out player clothing.

**Comment by Fogapod** [comment]
![image](https://user-images.githubusercontent.com/22667809/132567452-7247818e-fe76-4a0f-85de-1e12a4f16124.png)

**Comment by NoooneyDude** [comment]
@Fogapod staging or Solidarity?

**Comment by Fogapod** [comment]
Staging, seen this a couple of times that day

**Comment by Aranclanos** [comment]
Has it been happening after #7647 ?

One assumption is that the sprites changes messages arrived before the objects were created on the client
