### ISSUE TITLE
You can use right-click menu to pour out the reagents in anything, to disastrous results.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5311]
## Description
For some odd reason, you can use the right click menu on any reagent container to empty its contents even if you really shouldn't be able to do so. This includes things like food items, welding tools, and _entire welding fuel tanks_. In the case of the latter two examples this creates plasma in the atmosphere which isn't good.

![oh god why](https://cdn.discordapp.com/attachments/668605946691452949/766021069928661032/unknown.png)

### Steps to Reproduce
1.  Right click on a fuel tank as pictured above.
2.  Go to the Pour out (sic) option.
3.  Watch as the atmosphere becomes filled with plasma.

**Comment by MrAsbestos** [comment]
I think this is already fixed

**Comment by PetMudstone** [comment]
Not yet fixed, you can still empty the contents of any item. Welding fuel no longer produces plasma tho yay.
