### ISSUE TITLE
Admin respawn is broken currently

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#5417]
the player spawns in without the  traits been set, clothing, something to do with slot populated
----------------------------------------------------------------
NullReferenceException: Object reference not set to an instance of an object
PlayerSprites.SetupCustomisationSprite (CustomisationType customisationType, System.String customisationKey, System.String customisationName, System.Nullable`1[T] color) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Player/PlayerSprites.cs:155)
PlayerSprites.SetupAllCustomisationSprites () (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Player/PlayerSprites.cs:128)
PlayerSprites.SetupCharacterData (CharacterSettings Character) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Player/PlayerSprites.cs:118)
PlayerSprites.OnCharacterSettingsChange (CharacterSettings characterSettings) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Player/PlayerSprites.cs:291)
PlayerSpawn.ServerTransferPlayer (Mirror.NetworkConnection conn, UnityEngine.GameObject newBody, UnityEngine.GameObject oldBody, EVENT eventType, CharacterSettings characterSettings, System.Boolean willDestroyOldBody) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Core/Lifecycle/PlayerSpawn.cs:454)
PlayerSpawn.ServerGhostReenterBody (Mirror.NetworkConnection forConnection, UnityEngine.GameObject fromObject, Mind forMind) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Core/Lifecycle/PlayerSpawn.cs:209)
PlayerNetworkActions.GhostEnterBody () (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:609)
PlayerNetworkActions.ServerAGhost (System.String adminId, System.String adminToken) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:765)
PlayerNetworkActions.CallCmdAGhost (System.String adminI
------------------------------------------------------------
NullReferenceException: Object reference not set to an instance of an object
NamedSlotStoragePopulator.PopulateItemStorage (ItemStorage toPopulate, PopulationContext context) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Systems/Inventory/Populators/Storage/NamedSlotStoragePopulator.cs:42)
AutoOccupationStoragePopulator.PopulateItemStorage (ItemStorage toPopulate, PopulationContext context) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Systems/Inventory/Populators/Storage/AutoOccupationStoragePopulator.cs:25)
ItemStorage.ServerPopulate (IItemStoragePopulator populator, PopulationContext context) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Systems/Inventory/ItemStorage.cs:199)
ItemStorage.OnSpawnServer (SpawnInfo info) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Systems/Inventory/ItemStorage.cs:69)
Spawn._ServerFireClientServerSpawnHooks (SpawnResult result) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Core/Lifecycle/Spawn.cs:378)
PlayerSpawn.ServerSpawnInternal (Mirror.NetworkConnection connection, Occupation occupation, CharacterSettings characterSettings, Mind existingMind, System.Nullable`1[T] spawnPos, System.Boolean spawnItems, System.Boolean willDestroyOldBody) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Core/Lifecycle/PlayerSpawn.cs:189)
PlayerSpawn.ServerRespawnPlayer (Mind forMind) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Core/Lifecycle/PlayerSpawn.cs:75)
Antagonists.AntagManager+<ServerRespawnAsAntag>d__13.MoveNext () (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Systems/Antagonists/AntagManager.cs:110)
UnityEngine.SetupCoroutine.Invo
-----------------------------------------------------------------
NullReferenceException: Object reference not set to an instance of an object
NamedSlotStoragePopulator.PopulateItemStorage (ItemStorage toPopulate, PopulationContext context) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Systems/Inventory/Populators/Storage/NamedSlotStoragePopulator.cs:42)
AutoOccupationStoragePopulator.PopulateItemStorage (ItemStorage toPopulate, PopulationContext context) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Systems/Inventory/Populators/Storage/AutoOccupationStoragePopulator.cs:25)
ItemStorage.ServerPopulate (IItemStoragePopulator populator, PopulationContext context) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Systems/Inventory/ItemStorage.cs:199)
ItemStorage.OnSpawnServer (SpawnInfo info) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Systems/Inventory/ItemStorage.cs:69)
Spawn._ServerFireClientServerSpawnHooks (SpawnResult result) (at Q:/Fast programmes/Unity station_unity station/unitystation/UnityProject/Assets/Scripts/Core/Lifecycle/Spawn.cs:378)
PlayerSpawn.ServerSpawnInternal (Mirror.NetworkConnection connection, Occupation occupation, CharacterSettings characterSettings, Mind existingMind, System.Nullable`1[T] spawnPos, System.Boolean spawnItems, System.Boolean willDestroyOldBody)

**Comment by corp-0** [comment]
This was addressed in #5412 . After testing it we can close.

**Comment by NoooneyDude** [comment]
I've heard that the issue still exists, so I'm no longer sure if my changes created/removed the issue.
