### ISSUE TITLE
Dynamic UI duplicates when you restart many times the round

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7757]
### Environment
- Game Version: Staging 21110423
- OS Version: Arch Linux

### Detailed description of bug

When you end and start the round without logging off many times your UI will duplicate eventually (i used vote restart and admin quick end round).

![UI](https://user-images.githubusercontent.com/80334192/140615772-f37c048f-8ff6-4664-b2a0-7ccbb5a5eee5.png)

this errors show when the bug happens and i try to place stuff on the duplicated slots

[errorUI3.txt](https://github.com/unitystation/unitystation/files/7490792/errorUI3.txt)
[errorUI2.txt](https://github.com/unitystation/unitystation/files/7490793/errorUI2.txt)
[errorUI1.txt](https://github.com/unitystation/unitystation/files/7490794/errorUI1.txt)

### Steps to reproduce

1.vote restart or use admin end round 
2. repeat until bug shows

**Comment by Bod9001** [comment]
fixed in #7749

**Comment by CdrCross** [comment]
As of the 9th of April 2022 playtest, this is still happening. It happened for me after just one completed round.
![Unitystation_4zr0AQj1NW](https://user-images.githubusercontent.com/36482335/162628914-094e4828-e621-47a1-9c9e-808f28ba1f27.png)
.
